work_dir: ./work_dir/ntu/xview/agcn_joint_SlowFast_Tempool
model_saved_name: ./runs/ntu_cv_agcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/std/zhuyiran/Projects/ST-GCN/data/NTU-RGB-D/xview/train_data.npy
  label_path: /home/std/zhuyiran/Projects/ST-GCN/data/NTU-RGB-D/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/std/zhuyiran/Projects/ST-GCN/data/NTU-RGB-D/xview/val_data.npy
  label_path: /home/std/zhuyiran/Projects/ST-GCN/data/NTU-RGB-D/xview/val_label.pkl

# model
model: model.agcn_tempool_slowfast.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [1]
batch_size: 2
test_batch_size: 2
num_epoch: 50
nesterov: True
